root: '/home/kp600168/.torch/data/'
batch_size: 100
lr_256: 0.0512
epochs: 150
dataset: 'semi_50_mnist'
num_workers: 0
model: 'Ladder_MLP'

hydra:
  run:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}