root: '/gdata/MNIST/'
batch_size: 100
lr_256: 0.00512
epochs: 150
dataset: 'semi_10_mnist_gz'
num_workers: 4
model: 'Ladder_MLP'

hydra:
  run:
    dir: /userhome/outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}