root: '/home/kp600168/.torch/data/'
batch_size: 128
lr_256: 0.002
epochs: 150
dataset: 'semi_10_mnist'
num_workers: 0
model: 'toynet'
vae: 'VAE'

hydra:
  run:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}